services:
  subbridge:
    build: .
    image: remnawave-subbridge:latest
    container_name: subbridge
    restart: always
    env_file: .env
    network_mode: host
    volumes:
      - ./bridge.py:/app/bridge.py:ro
      - ./import_users.py:/app/import_users.py:ro
